go:
  - 1.4
  - 1.5.1

install:
  - export PATH=$GOPATH/bin:./_tools/etcd/bin:$PATH
  - make install-travis

deploy:
  - provider: s3
    access_key_id: AKIAO27MPEIWV3GJ56EQ
    secret_access_key:
      secure: Q9Dxc3YHZH2IhZ4aeUYna1ZeLK8kSRTwoPFtPHAf/oL6sGRjpcmLCgjHBDhTioW+WimAVtwNfvvz5ApNVRi539c9x5zEUmj6+hOQqP5ieiJ2ByVAO2oAkmf327x2O4kZwXkirKBWq82NgY4o8RbGnNhdgYLRZX41Twyzc1892WiC/ADUEqQV72LGgtxBG8zh4dHc+gurrBhbHq3hO5E+vlfUTOuLfmg7jRr0T9fN31AbHUPkTTlDc+K2fJ7XDqxE8MctpPDlWQ85EiavySTGOY0+HDnQ+zePBxxe1DJAVYi/CFceUX5Dox9Bt8aQKkXHNsFuDDDFEBYPk1FDlVmrkYiy4DBYbM9PgfH6Z9vk0t0kRpwr5mY2fzcY2cMkj6icx/lgiZm7OO3fb1scr4SIlYRAp69k5TlnjQIHAeN6/sSttJkfZW4SBUTsDsSJhxBh3rCIY2QhLhsL7Xwp/VSWwCZHndNkdp5HwAS7+u3JmTOpMOXGT2ExgxdLD87+H34MOGrbiNCw3iJFk+jFk7KAyyGPTVgWx5ZypQQy4kHsyfk1qfBThMJKJnYxCdv99Kw8NNKQdMOjq3Eh3PWxHjE+bjzRjxSTDdP2HqGd0Mau9UofZiYgwKQF7/0pVf4n6bVnrvKnQmX7G/3OGZYhEtHoMMiApRfo5pR8tmH0/rTXvPI=
    bucket: asiainfo-datafactory-bin
    upload-dir: develop
    local-dir: _output/local/bin/linux/amd64/
    region: cn-north-1
    acl: ''
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
  - provider: releases
    api_key:
      secure: YXnRO3hJxpVizfzXb5RWu8zYtRyW8q6WEmjuvR6xOwaboTq8mNOEPptfryE0yhaO9Lv68Xf5VB26HLuiTaPivIIomB2QCOo+rQT9GNho5CFPomKW9gk+yhxKAlCZzorfqRyJErr6zyVWaajfdVeLbB6B7MKY+5/bAc5QHYyDW2fLZnQq1wrXkeuFEmmpPbdxincTwjhlRtbbJSCRLaI9SuE9S7JWS5OhLtgEGVu6DY+BQi1PXcwwpAzvLbrr3yt9t+LvyKzvKNXe02bAvp2/Q4cOhKb/7eg8LxjaBwmpk5nLrqx9b3UrMS5Rk9P2J/U75GsQRM4ebGzK7N+FvLWj+8uxT9tDHY3+5g1a2sUzMfdLaSAx6qeleqOqxlvbujzQVlaBhdjxDN5pRLbqQilmM6ezF7/vJ2Y8HXNSfvg1ZsYQ2y1ZP0V42hfsPCs9g8Ro3/buxhqoaIll+rfvJSOipvfS0TjEEfs6/36WsDCpZj94me48ZY4e1FblgaDU0Xa0tseE2froN7X0zLjfLTOFbjbEY96bLwNmnehEBbBiQ80nwjoTj1L+WARTiUtffTrVFYysBCct7fsk/jn9sh2bd4sMXLMvpRbujlXyjP8vvqIxplEwXaKHwRj2IWkbk8Kr6Lf5JSCQspr8z/kT2JVQCwLEoqPsbQOD26stsgGqW6I=
    file: 
      - "_output/local/bin/linux/amd64/oc"
      - "_output/local/bin/linux/amd64/openshift"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
    
sudo: false
